GET http://localhost:8080/api/user/createUser

####

POST http://localhost:8080/api/user/createUser
Content-Type: application/json

{
  "username":"barunkumar",
  "email":"barun.kumar@gmail.com",
  "password":"123456"
}

####

POST http://localhost:8080/api/user/signinUser
Content-Type: application/json

{
  
  "email":"kbarun.kumar@gmail.com",
  "password":"123456"
}